subsystem_dict = {'Acyl-CoA hydrolysis': ['HMR_0272'],
                  'Acylglycerides metabolism': ['HMR_0670', 'HMR_0681'],
                  'Alanine, aspartate and glutamate metabolism': ['HMR_3829', 'HMR_3899'],
                  'Amino sugar and nucleotide sugar metabolism': ['HMR_4158', 'HMR_4300', 'HMR_4628', 'HMR_4631'],
                  'Aminoacyl-tRNA biosynthesis': ['HMR_5130', 'HMR_5131', 'HMR_5132', 'HMR_5133', 'HMR_5134',
                      'HMR_5135','HMR_5136', 'HMR_5137', 'HMR_5138', 'HMR_5139', 'HMR_5140', 'HMR_5141', 'HMR_5142',
                      'HMR_5143','HMR_5145', 'HMR_5146', 'HMR_5147', 'HMR_5148', 'HMR_5149', 'HMR_5150'],
                  'Arginine and proline metabolism': ['HMR_3956', 'HMR_4190'],
                  'Artificial reactions': ['HMR_10063', 'HMR_10062', 'HMR_10064', 'HMR_10065'],
                  'Bile acid biosynthesis': ['HMR_1832', 'HMR_1834', 'HMR_1835', 'HMR_1841', 'HMR_1844', '3DHLCAS'],
                  'Biotin metabolism': ['HMR_7663'],
                  'Carnitine shuttle (cytosolic)': ['HMR_0159', 'HMR_2591', 'HMR_2594', 'HMR_2636', 'HMR_2742'],
                  'Carnitine shuttle (mitochondrial)': ['HMR_0161', 'HMR_2593'],
                  'Cysteine and methionine metabolism': ['HMR_3877', 'HMR_3920', 'r0193'],
                  'Exchange/demand reactions': ['HMR_9809', 'HMR_9815', 'HMR_9034' , 'HMR_9038'
     , 'HMR_9039' , 'HMR_9042' , 'HMR_9043' , 'HMR_9044' , 'HMR_9045' , 'HMR_9046'
                      , 'HMR_9048'
                      , 'HMR_9051'
                      , 'HMR_9055'
                      , 'HMR_9062'
                      , 'HMR_9063'
                      , 'HMR_9064'
                      , 'HMR_9067'
                      , 'HMR_9068'
                      , 'HMR_9069'
                      , 'HMR_9072'
                      , 'HMR_9078'
                      , 'HMR_9085'
                      , 'HMR_9103'
                      , 'HMR_9107'
                      , 'HMR_9108'
                      , 'HMR_9110'
                      , 'HMR_9133'
                      , 'HMR_9135'
                      , 'HMR_9141'
                      , 'HMR_9146'
                      , 'HMR_9147'
                      , 'HMR_9152'
                      , 'HMR_9154'
                      , 'HMR_9155'
                      , 'HMR_9159'
                      , 'HMR_9167'
                      , 'HMR_9215'
                      , 'HMR_9235'
                      , 'HMR_9242'
                      , 'HMR_9253'
                      , 'HMR_9254'
                      , 'HMR_9262'
                      , 'HMR_9269'
                      , 'HMR_9271'
                      , 'HMR_9273'
                      , 'HMR_9285'
                      , 'HMR_9290'
                      , 'HMR_9292'
                      , 'HMR_9348'
                      , 'HMR_9351'
                      , 'HMR_9354'
                      , 'HMR_9358'
                      , 'HMR_9372'
                      , 'HMR_9378'
                      , 'HMR_9383'
                      , 'HMR_9404'
                      , 'HMR_9406'
                      , 'HMR_9418'
                      , 'HMR_9421'
                      , 'HMR_9422'
                      , 'HMR_9437'
                      , 'HMR_9440'
                      , 'HMR_9450'
                      , 'HMR_9456'
                      , 'HMR_9463'
                      , 'HMR_9690'
                      , 'HMR_9691'
                      , 'HMR_9729'
                      , 'EX_atp[e]'
                      , 'EX_dlnlcg[e]'
                      , 'EX_lpchol_hs[e]'
                      , 'EX_ocdcea[e]'
                      , 'EX_pe_hs[e]'
                      , 'EX_pglyc_hs[e]'
                      , 'EX_ps_hs[e]'
                      , 'EX_ttdca[e]'
                      , 'EX_ahdt[e]'
                      , 'EX_fad[e]'
                      , 'EX_HC02192[e]'
                      , 'EX_HC02193[e]'
                      , 'EX_HC02191[e]'
                      , 'EX_crm_hs[e]'
                      , 'EX_c10crn[e]'
                      , 'EX_c4crn[e]'
                      , 'EX_tdechola[e]'
                      , 'EX_q10[e]'
                      , 'EX_ahcys[e]'
                      , 'EX_2pg[e]'
                      , 'EX_dcmp[e]'
                      , 'EX_pep[e]'
                      , 'EX_xmp[e]'
                      , 'EX_orot5p[e]'
                      , 'EX_glyc3p[e]'
                      , 'EX_pcrn[e]'
                      , 'EX_odecrn[e]'
                      , 'EX_pmtcrn[e]'
                      , 'EX_forglu[e]'
                      , 'EX_HC00900[e]'
                      , 'EX_hxcoa[e]'
                      , 'EX_lnlccrn[e]'
                      , 'EX_nwharg[e]'
                      , 'EX_pser_L[e]'
                      , 'EX_thbpt[e]'
                      , 'EX_argcysgly[e]'
                      , 'EX_cyscys[e]'
                      , 'EX_glylyscys[e]'
                      , 'EX_lysargleu[e]'
                      , 'EX_hxa[e]'
                      , 'EX_pcreat[e]'
                      , 'EX_glcn[e]'
                      , 'EX_fum[e]'
                      , 'EX_nh4[e]'
                      , 'EX_glcur[e]'
                      , 'EX_CE1401[e]'
                      , 'EX_xylu_D[e]'
                      , 'EX_sphings[e]'
                      , 'EX_mlthf[e]'
                      , 'EX_sphgn[e]'
                      , 'EX_1a25dhvitd3[e]'
                      , 'EX_fdp[e]'
                      , 'EX_3dhlchol[e]'
                      , 'HMR_10024'
                      , 'HMR_10047'],
                  'Fatty acid activation (cytosolic)': ['HMR_0156', 'HMR_0168', 'HMR_0188', 'HMR_0192', 'HMR_0196',
                                                        'HMR_0200', 'HMR_0204', 'HMR_0209', 'HMR_0213', 'HMR_0217',
                                                        'HMR_0226',
                                                        'HMR_0233', 'HMR_0237', 'HMR_0241', 'HMR_0245',
                                                        'HMR_0249', 'HMR_0255', 'HMR_0259', 'HMR_0267', 'HMR_0275',
                                                        'HMR_0279',
                                                        'HMR_0283', 'HMR_0289', 'HMR_0293'
                      , 'HMR_0297', 'HMR_0301', 'HMR_0305', 'HMR_0309', 'HMR_0313', 'HMR_0319', 'HMR_0323'
                      , 'HMR_0327', 'HMR_0331', 'HMR_0337', 'HMR_0341', 'HMR_0345', 'HMR_0349'
                      , 'HMR_0353', 'HMR_0357', 'HMR_0361', 'HMR_0365', 'HMR_0369', 'HMR_0373', 'HMR_0377'
                      , 'HMR_0381', 'HMR_0385', 'HMR_0389', 'HMR_0393', 'HMR_0397', 'HMR_0401', 'HMR_0405'
                      , 'HMR_0409', 'HMR_0413', 'HMR_0417', 'HMR_0421', 'HMR_0425', 'HMR_0429', 'HMR_0433', 'HMR_0437'],
                  'Fatty acid biosynthesis': ['DESAT18_10', 'DESAT18_9'],
                  'Fatty acid oxidation': ['C181CPT1', 'TMNDNCCRNt', 'r1400', 'FAOXC6C4m', 'SUBERCACT', 'HXCOAc',
                                           'HXCOAx'],
                  'Folate metabolism': ['HMR_3929', 'HMR_3972', 'HMR_4335', 'HMR_4655', 'HMR_4656', 'HMR_8132',
                                        'HMR_8144'],
                  'Galactose metabolism': ['HMR_3944', 'HMR_4131', 'HMR_8767'],
                  'Glutathione metabolism': ['HMR_4116'],
                  'Glycerophospholipid metabolism': ['HMR_0579', 'HMR_0580', 'HMR_0581', 'HMR_0586', 'HMR_0598',
                                                     'HMR_0632'],
                  'Glycine, serine and threonine metabolism': ['HMR_4584'],
                  'Glycolysis / Gluconeogenesis': ['HMR_3905', 'HMR_4137', 'HMR_4388', 'HMR_8357', 'HMR_4301',
                                                   'HMR_4355',
                                                   'HMR_4363'
                      , 'HMR_4365', 'HMR_4368', 'HMR_4371', 'HMR_4373', 'HMR_4375', 'HMR_4381', 'HMR_4391', 'HMR_4396'],
                  'Histidine metabolism': ['HMR_4658'],
                  'Miscellaneous': ['HMR_4201', 'HMR_5127', 'HMR_8617', 'r0707', 'r1433', 'EX_pail_hs[e]'],
                  'Nicotinate and nicotinamide metabolism': ['HMR_4262', 'HMR_4269', 'NMNATr'],
                  'Nucleotide metabolism': ['HMR_3968', 'HMR_4026'
                      , 'HMR_4083'
                      , 'HMR_4633'
                      , 'HMR_4680'
                      , 'HMR_7160'
                      , 'HMR_7161'
                      , 'HMR_7717'
                      , 'HMR_7800'
                      , 'HMR_7867'
                      , 'HMR_7875'
                      , 'HMR_7883'
                      , 'HMR_8443'
                      , 'HMR_8477'
                      , 'HMR_8486'
                      , 'HMR_8488'
                      , 'HMR_8489'],
                  'Oxidative phosphorylation': ['HMR_6916', 'HMR_6918', 'HMR_6921', 'CYOOm3i'],
                  'Pentose and glucuronate interconversions': ['HMR_4595'],
                  'Pentose phosphate pathway': ['HMR_4304'
                      , 'HMR_4350'
                      , 'HMR_4352'
                      , 'HMR_4354'
                      , 'HMR_4398'
                      , 'HMR_4404'
                      , 'HMR_4476'
                      , 'HMR_4501'
                      , 'HMR_4565'
                      , 'HMR_4568'
                      , 'HMR_4623'
                      , 'HMR_4710'
                      , 'G6PDH2c'
                      , 'PGLc'
                      , 'RPEc'],
                  'Peptide metabolism': ['ARGCYSGLYr'
                      , 'CYSCYSr'
                      , 'GLYLYSCYSr'
                      , 'LYSARGLEUr'],
                  'Phenylalanine, tyrosine and tryptophan biosynthesis': ['HMR_6725'],
                  'Pool reactions': ['HMR_0014', 'HMR_10033', 'HMR_10036'],
                  'Purine metabolism': ['HMR_4002'
                      , 'HMR_4004'
                      , 'HMR_4081'
                      , 'HMR_4012'
                      , 'HMR_4020'
                      , 'HMR_4085'
                      , 'HMR_4135'
                      , 'HMR_4171'
                      , 'HMR_4418'
                      , 'HMR_4421'
                      , 'HMR_4452'
                      , 'HMR_4480'
                      , 'HMR_4573'
                      , 'HMR_4614'
                      , 'HMR_4621'
                      , 'HMR_4651'
                      , 'HMR_4695'
                      , 'HMR_7144'
                      , 'HMR_4420'
                      , 'ADNK3'
                      , 'ADNK4'],
                  'Pyrimidine metabolism': ['HMR_4006'
                      , 'HMR_4030'
                      , 'HMR_4670'
                      , 'HMR_4675'
                      , 'HMR_6616'
                      , 'HMR_3931'
                      , 'HMR_3970'
                      , 'HMR_4032'
                      , 'HMR_4210'
                      , 'HMR_4484'
                      , 'HMR_4485'
                      , 'HMR_4512'
                      , 'HMR_4514'
                      , 'HMR_4577'
                      , 'HMR_4579'
                      , 'HMR_4575'
                      , 'HMR_4637'
                      , 'HMR_4644'
                      , 'HMR_6612'
                      , 'HMR_6621'
                      , 'HMR_6627'],
                  'ROS detoxification': ['HMR_3960', 'HMR_3980', 'HMR_3982', 'HMR_4767', 'HMR_8410'],
                  'Retinol metabolism': ['HMR_6632'
                      , 'HMR_6634'
                      , 'HMR_6638'
                      , 'HMR_6641'
                      , 'HMR_6642'
                      , 'HMR_6644'
                      , 'HMR_6648'
                      , 'HMR_6649'
                      , 'HMR_6650'
                      , 'HMR_6651'
                      , 'HMR_6654'
                      , 'HMR_6655'
                      , 'HMR_6656'
                      , 'HMR_6657'
                      , 'HMR_6658'
                      , 'HMR_6659'
                      , 'HMR_6660'
                      , 'HMR_6661'
                      , 'HMR_6662'
                      , 'HMR_6664'
                      , 'HMR_6665'
                      , 'HMR_6668'
                      , 'HMR_6669'
                      , 'HMR_6673'
                      , 'HMR_6675'
                      , 'HMR_6677'
                      , 'HMR_6678'
                      , 'HMR_6682'
                      , 'HMR_6687'
                      , 'HMR_6690'
                      , 'HMR_6691'
                      , 'HMR_6692'
                      , 'HMR_6693'
                      , 'HMR_6700'
                      , 'HMR_6701'
                      , 'HMR_6702'
                      , 'HMR_6703'
                      , 'HMR_8698'
                      , 'HMR_8702'],
                  'Riboflavin metabolism': ['HMR_6507', 'HMR_6509'],
                  'Sphingolipid metabolism': ['HMR_0736', 'HMR_0753', 'HMR_0758', 'RE2675C', 'CRMte'],
                  'Starch and sucrose metabolism': ['HMR_4122'
                      , 'HMR_5395'
                      , 'HMR_5396'
                      , 'HMR_5397'
                      , 'HMR_5398'
                      , 'HMR_5399'
                      , 'HMR_5400'
                      , 'HMR_5401'],
                  'Steroid metabolism': ['UGT1A10r'],
                  'Thiamine metabolism': ['HMR_4204'],
                  'Transport reactions': ['HMR_0018'
                      , 'HMR_0179'
                      , 'HMR_0195'
                      , 'HMR_0262'
                      , 'HMR_0404'
                      , 'HMR_0444'
                      , 'HMR_3959'
                      , 'HMR_4063'
                      , 'HMR_4845'
                      , 'HMR_4847'
                      , 'HMR_4848'
                      , 'HMR_4882'
                      , 'HMR_4885'
                      , 'HMR_4896'
                      , 'HMR_4947'
                      , 'HMR_4948'
                      , 'HMR_4958'
                      , 'HMR_4969'
                      , 'HMR_4980'
                      , 'HMR_4990'
                      , 'HMR_4992'
                      , 'HMR_5032'
                      , 'HMR_5037'
                      , 'HMR_5070'
                      , 'HMR_5078'
                      , 'HMR_5082'
                      , 'HMR_5088'
                      , 'HMR_5089'
                      , 'HMR_5091'
                      , 'HMR_5092'
                      , 'HMR_5296'
                      , 'HMR_5303'
                      , 'HMR_5436'
                      , 'HMR_5462'
                      , 'HMR_5907'
                      , 'HMR_6038'
                      , 'HMR_6049'
                      , 'HMR_6060'
                      , 'HMR_6068'
                      , 'HMR_6071'
                      , 'HMR_6108'
                      , 'HMR_6250'
                      , 'HMR_6381'
                      , 'HMR_6424'
                      , 'HMR_6439'
                      , 'HMR_6512'
                      , 'HMR_6529'
                      , 'HMR_6628'
                      , 'HMR_7735'
                      , 'HMR_7898'
                      , 'HMR_7905'
                      , 'HMR_8010'
                      , 'HMR_8408'
                      , 'HMR_8612'
                      , 'HMR_8676'
                      , 'HMR_9173'
                      , 'HMR_9183'
                      , 'HMR_9189'
                      , 'HMR_9608'
                      , 'HMR_9617'
                      , 'HMR_9641'
                      , 'HMR_9728'
                      , 'HMR_0158'
                      , 'HMR_0578'
                      , 'HMR_0587'
                      , 'HMR_2127'
                      , 'HMR_2141'
                      , 'HMR_3789'
                      , 'HMR_3952'
                      , 'HMR_4760'
                      , 'HMR_4843'
                      , 'HMR_4852'
                      , 'HMR_4854'
                      , 'HMR_4888'
                      , 'HMR_4898'
                      , 'HMR_4926'
                      , 'HMR_4957'
                      , 'HMR_5006'
                      , 'HMR_5031'
                      , 'HMR_5033'
                      , 'HMR_5043'
                      , 'HMR_6287'
                      , 'HMR_6294'
                      , 'HMR_6332'
                      , 'HMR_6334'
                      , 'HMR_6431'
                      , 'HMR_6438'
                      , 'HMR_6446'
                      , 'HMR_6454'
                      , 'HMR_7638'
                      , 'HMR_7719'
                      , 'HMR_7815'
                      , 'HMR_8009'
                      , 'HMR_8475'
                      , 'HMR_8614'
                      , 'HMR_8891'
                      , 'HMR_8639'
                      , 'HMR_3953'
                      , 'HMR_4765'
                      , 'HMR_4856'
                      , 'HMR_4883'
                      , 'HMR_4894'
                      , 'HMR_6629'
                      , 'HMR_7778'
                      , 'HMR_7780'
                      , 'HMR_8722'
                      , 'ACRNtm'
                      , 'BILDGLCURtr'
                      , 'BTNt4i'
                      , 'CLPNDCOAtx'
                      , 'FOLt2'
                      , 'GLCt2_2'
                      , 'LPCHOLt'
                      , 'NAHCO3_HCLt'
                      , 'NH4t3r'
                      , 'PEt'
                      , 'PGLYCt'
                      , 'PSt3'
                      , 'XOLEST2te'
                      , 'r0941'
                      , 'r1147'
                      , 'r1423'
                      , 'r2377'
                      , 'PIt8'
                      , 'C4tmc'
                      , 'Coqe'
                      , 'PPItm'
                      , 'TAURCHAe'
                      , 'q10tm'
                      , 'AHCYSte'
                      , 'OROTGLUt'
                      , 'PEPtr'
                      , '2PGtr'
                      , 'DCMPtr'
                      , 'FUMtr'
                      , 'GLCURtr'
                      , 'XMPtr'
                      , 'GLYC3tr'
                      , 'OROT5Ptr'
                      , 'BUTSMCT1'
                      , 'FOLOAT2tc'
                      , 'METB0AT3tc'
                      , 'PYRSMCT1'
                      , 'TYRB0AT3tc'
                      , 'PCRNte'
                      , 'ODECRNte'
                      , 'PCREATte'
                      , 'C05463t2'
                      , 'FORGLUt'
                      , 'HC00900t2'
                      , 'HC00900t4'
                      , 'HXCOAte'
                      , 'NWHARGtd'
                      , 'PSERtr'
                      , 'THBPTt'
                      , 'ARGCYSGLYt'
                      , 'CYSCYSt'
                      , 'GLYLYSCYSt'
                      , 'LYSARGLEUt'
                      , 'C10CRNtr'
                      , 'C4CRNtr'
                      , 'C8DCtr'
                      , 'HDCECRNtr'
                      , 'LNLCCRNtr'
                      , 'PMTCRNtr'
                      , 'HXAt3'
                      , 'PGLYCtm'
                      , 'BUTt2r'
                      , 'THMt3'
                      , 'PAIL_hs_t1e'
                      , 'MLTHFte3'
                      , '1A25DHVITD3te'
                      , 'CE1401te'
                      , 'XYLUDte'
                      , 'GLCNte'
                      , 'SPHGNte'
                      , 'FDPte'
                      , '3DHLCAt'
                      , 'DCMPtm'
                      , 'HMR_10023'
                      , 'HMR_10046'],
                  'Tricarboxylic acid cycle and glyoxylate/dicarboxylate metabolism': ['HMR_4139', 'HMR_4141',
                                                                                       'HMR_4145',
                                                                                       'HMR_4147',
                                                                                       'HMR_4410', 'HMR_4456',
                                                                                       'HMR_4652',
                                                                                       'HMR_5297'],
                  'Valine, leucine, and isoleucine metabolism': ['HMR_3215', 'HMR_3763'],
                  'Vitamin A metabolism': ['RE1905C'],
                  'Vitamin B12 metabolism': ['HMR_8613', 'HMR_8615', 'HMR_8616'],
                  'Vitamin D metabolism': ['HMR_2129'
                      , 'HMR_2130'
                      , 'HMR_2131'
                      , 'HMR_2132'
                      , 'HMR_2133'
                      , 'HMR_2134'
                      , 'HMR_2135'
                      , 'HMR_2136'
                      , 'HMR_2137'
                      , 'HMR_2139'
                      , 'HMR_2142'
                      , 'HMR_2143'
                      , 'HMR_2144'
                      , 'HMR_2145']}

import pickle

# save pickle object to obj folder
def save_obj(obj, name):
    with open('../../obj/dicts/' + name + '.pkl', 'wb') as f:
        pickle.dump(obj, f,  protocol = 2)

def load_obj(name ):
    with open('../obj/' + name + '.pkl', 'rb') as f:
        return pickle.load(f)


save_obj(subsystem_dict, "subsystem_dict")